volumes:
  postgres_volume:
  rabbitmq_data:

services:
  db_manager:
    build: db_manager/
    restart: no
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://user:password@db:5432/docker_db
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
    stdin_open: true
    tty: true

  client_app:
    build: client_app/
    restart: no
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      db_manager:
        condition: service_started
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
    stdin_open: true
    tty: true


  db:
    image: postgres:alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: docker_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d docker_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "8080:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
